version: "3"
services:

  nginx:
    build: ./nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./assets/css:/var/www/css
    - ./assets/vendor:/var/www/vendor
    - ./assets/html:/var/www/html
    ports:
      - 8080:80
    depends_on: 
      - php

  php:
    build: ./php
    volumes:
    - ./assets:/var/www
    - ./assets/html:/var/www/html
    - ./assets/css:/var/www/css
    - ./assets/vendor:/var/www/vendor
    depends_on: 
    - db
  
  db:
    image: mysql:5.7
    ports:
    - 13306:3306
    volumes:
    - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
    command: --innodb_use_native_aio=0   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports: 
    - 8888:80
    depends_on: 
    - db
    environment:
      PMA_HOST: db